name: PR Comment

on:
  pull_request:
    branches: ["*"]

jobs:
  Coment:
    runs-on: ubuntu-latest
    steps:      
      - env:
          PR_NUMBER: ${{ github.event.pull_request.number }} 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export body=$( curl ifconfig.co/json)
          export ip=$(echo $body | jq '.ip')
          export co=$( echo $body | jq '.country')
          gh pr comment $PR_NUMBER --body "This was run from address: $ip located at $co" --repo $GITHUB_REPOSITORY

