name: PR Comment

on:
  pull_request:
    branches: ["*"]

jobs:
  Comments:
    runs-on: ubuntu-latest
    steps:      
      - env:
          PR_NUMBER: ${{ github.event.pull_request.number }} 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export body=$( curl http://ip.jsontest.com/)
          export ip=$(echo $body | jq 'Accept-Language')
          export co=$( echo $body | jq 'Accept-Charset')
          gh pr comment $PR_NUMBER --body "This was run from address: $ip located at $co" --repo $GITHUB_REPOSITORY

