name: PR Comment

on:
  pull_request:
    branches: ["*"]

jobs:
  Comments:
    runs-on: ubuntu-latest
    steps:      
      - env:
          PR_NUMBER: ${{ github.event.pull_request.number }} 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export body=$( curl 'countries-cities.p.rapidapi.com/location/country/list')
          export ip=$(echo $body | jq '.AE')
          export co=$( echo $body | jq '.SA')
          gh pr comment $PR_NUMBER --body "This was run from address: $ip located at $co" --repo $GITHUB_REPOSITORY

